# Generated by Django 6.0.6 on 2026-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawmodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='law_icons/'),
        ),
        migrations.AlterField(
            model_name='lawmodel',
            name='is_free',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
