# Generated by Django 6.1.1 on 2026-09-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userhistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
