# Generated by Django 6.1.1 on 2026-09-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chaptermodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
